version: "3.7"

services:
  jupyterlab:
    env_file:
      - .env
    build: 
      context: ./alex_mlwml
      dockerfile: ./Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
        USER: ${USER}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    container_name: ${JUPYTERLAB_CONTAINER_NAME}
    networks:
      - docker_net0
    environment: 
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
      - TZ=Europe/Madrid
      - NB_UID=${UID}
      - NB_GID=${GID}
      - JUPYTER_TOKEN=${JUPYTER_PASSWORD}
    user: "${UID}:${GID}"
    volumes:
      - "${PWD}:/home/${USER}/work"
    ports:
      - "${JUPYTERLAB_PORT}:8888"
    expose:
      - "${JUPYTERLAB_PORT}"
    restart: always

networks:
  docker_net0:
    driver: bridge

