version: "3.8"

services:
  jupyterlab:
    build: 
      context: ./image
      dockerfile: ./Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        USERNAME: ${USERNAME:-jupyter}
    image: jupyterlab-${CONTAINER_NAME}:latest
    container_name: ${CONTAINER_NAME:-simple-jupyterlab}
    environment: 
      - JUPYTER_ENABLE_LAB=yes
      - NB_UID=${UID:-1000}
      - NB_GID=${GID:-1000}
      - JUPYTER_TOKEN=${JUPYTER_PASSWORD:-password}
    ports:
      - "${JUPYTER_PORT:-8888}:8888"
    volumes:
      - ./workspace:/home/${USERNAME:-jupyter}/workspace
    user: "${UID:-1000}:${GID:-1000}"
    restart: unless-stopped