version: '3'
services:
    jupyterlab:
        env_file:
            - .env
        build: 
            context: .
            dockerfile: image/Dockerfile
            args:
                UID: \${UID}
                GID: \${GID}
                USERNAME: \${USERNAME}
                JUPYTERLAB_PORT: \${JUPYTERLAB_PORT}
        image: jupyterlab-\${CONTAINER_NAME}:latest
        container_name: \${CONTAINER_NAME}
        environment: 
            - JUPYTER_ENABLE_LAB=yes
            - NB_UID=\${UID}
            - NB_GID=\${GID}
            - JUPYTER_TOKEN=\${JUPYTER_PASSWORD}
        ports:
            - \${JUPYTERLAB_PORT}:\${JUPYTERLAB_PORT}
        volumes:
$(echo -e "$VOLUMES_CONFIG")
        user: \${UID}:\${GID}
        restart: unless-stopped
        networks:
            - jupyter-network

networks:
    jupyter-network:
        driver: bridge