services:
  windows:
    image: dockurr/windows
    container_name: ${CONTAINER_NAME}
    environment:
      VERSION: "11"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - ${WEB_PORT}:8006
      - ${RDP_PORT}:3389/tcp
      - ${RDP_PORT}:3389/udp
    volumes:
      - ./windows:/storage
    restart: always
    stop_grace_period: 2m